print("Hello World!")
print(10 + 10)
print("10 + 10")
print("     xxxx")
print("  xxxxxxx")
print(" xxxxxxxx")
print("  xxxxxxx")
print("  x     x")
print("  xxxxxxx")
print("  xxxxxxx")
print("  x     x")
print("  xxxxxxx")